version: '3.9'
services:
  servCont1:
    image: t1
    ports:
      - 8081:8080
    container_name: cont_1
    environment:
      MY_SOME_VAR: some var
    restart: always

  servCont2:
    image: t2
    ports:
      - 8082:8080
    container_name: cont_2
    links:
      - servCont1

  servCont3:
    build: .
    image: t3
    ports:
      - 8083:8080
    container_name: cont_3
    environment:
      MY_SOME_VAR: some var
    restart: always

  servCont45:
    build: .
    image: t4
    ports:
      - 8084-8085:8080 #for scaling
#    container_name: cont_3  #not need for scaling
    environment:
      MY_SOME_VAR: some var
    restart: always